export const usernames = [
  'Tejas',
  'SAGAR JAISWAL',
  'Saddaquat Hussain',
  'Mohit Ranjan',
  'Baap',
  'Shreyanshi Pundeer',
  'Chandan Kushwaha',
  'Shobhit Tandon',
  'Prasoon Mishra',
  'Aslam Mahmood',
  'Shekhar',
  'Vashu Sharma',
  'Tridev Kumar',
  'Mohd Sahdeen',
  'Anuj',
  'Jatav Ji',
  'Priyanka Singh',
  'Saumya',
  'Gift Cards',
  'Avi Jaiswal',
  'Pankaj Verma',
  'Akshay Mark',
  'Vikas Yadav',
  'Rishi Mishra',
  'Aakansha Sharma',
  'Satyam',
  'Amit Singh',
  'Avinash Kumar',
  'Kapish',
  'Abhishek Kumar',
  'Harshita',
  'Hardik Saxena',
  'Sarthak Agrawal',
  'Riya',
  'Gauravsingh',
  'Prem Jaiswar',
  'ADARSH SINGH',
  'Armatya Kumar',
  'Aditya Tripathi',
  'Gaurav',
  'Hrishique Munshi',
  'Pinku Kumar',
  'Abhijat Mishra',
  'Td',
  'Mohd Aarish',
  'Saumya',
  'R K Rai',
  'Uaish',
  'Ashish Pandit',
  'Ashu',
  'Kim Jong Un',
  'Abhay',
  'Arun Upadhyay',
  'Anushka Shukla',
  'Aniket Singh',
  'Ankita',
  'Sundar',
  'Rakesh Kumar',
  'AMAN KANSAL',
  'Nidhi Agnihotri',
  'Amit Rawat',
  'Ashit Kumar Rai',
  'Aakash',
  'Rahul Maheshwari',
  'Mo Shahzad',
  'Vishal Sharma',
  'Hemant Kumar',
  'Rubi Ansari',
  'Jyoti',
  'Dinesh Chandra',
  'Somya',
  'Abhinav',
  'AS',
  'Anuj Verma',
  'Aman Maurya',
  'Utkarsh Upadhyay',
  'Utkarsh Upadhyay',
  'Sanad',
  'Dipti Pathak',
  'Venktesh Singh',
  'Vidhi Srivastava',
  'SAAD QADIR',
  'Sanjay',
  'Mohd Zahid Malik',
  'Shivendra Srivastava',
  'Nandita',
  'Abhishek',
  'Anuj',
  'Ankur Singh',
  'Arpit Bisen',
  'Amarjeet Chauhan',
  'Gaurav',
  'Aman Tiwari',
  'Shivam Singh',
  'Gitanjali Singh',
  'Harshita Gupta',
  'Swapnil Dwivedi',
  'Aditi',
  'Deepak Pandey',
  'Narendra Dhakrey',
  'Akarsh Gangwar',
  'Kavya',
  'Ankit',
  'Pawan Kumar Rawat',
  'Rani',
  'Gaurav Pandey',
  'Venkat Sesha Sai',
  'ABHISHEK MISHRA',
  'Gaurav Jha',
  'Pravesh Tyagi',
  'Sujeet Kumar',
  'Tripti',
  'Setul Parmar',
  'UDDESHYA PATEL',
  'Manish Tiwari',
  'Jayant Kumar',
  'Satyendra Pratap Singh',
  'Sonali Gupta',
  'Arpita Kesharwani',
  'Sanidhya',
  'Harshita Tyagi',
  'Naman Aggarwal',
  'Harshit Katiyar',
  'Prerna Pranay',
  'Harsha',
  'Abhilash Kumar Parvat',
  'Sreya Singh',
  'Anupama Pandey',
  'Maan Singh Yadav',
  'Adrika Gupta',
  'Anushka Yadav',
  'Kunal Tripathi',
  'Supriya Sharma',
  'Shivansh',
  'BRIJESH',
  'Aarushi Agarwal',
  'Brijesh',
  'Preeti Singh',
  'Bobby Jaiswar',
  'KAUNAIN KAUSHAR',
  'Abhishek Srivastava',
  'Manish Singh',
  'Ajay Tripathi',
  'YOGESH PRAJAPATI',
  'ANANT',
  'Rishi SRIVASTAVA',
  'Sangram',
  'Misbah',
  'Aniket',
  'Avi Tripathi',
  'BRIJ BHUSHAN PRAJAPATI',
  'Siddharth Singh Kushwaha',
  'MOHIT SINGH',
  'Pranjal Mittal',
  'Vivek Tripathi',
  'Shivangi Verma',
  'Anirudh Sharma',
  'Neeraj Katheriya',
  'Richu',
  'Avi Chaurasia',
  'Hello Kaun',
  'Aditya',
  'Ashish Gupta',
  'NIKHIL GANGAL BLOGs',
  'Roopchand Sahu',
  'Mohd. Arif',
  'Pranjal',
  'Ashok Kumar',
  'Pallavee Maurya',
  'Harsh Pandey',
  'Dushyant',
  'Sunita Ku.',
  'Ã¤Âºâ€”TARUNÃ¤Âºâ€”',
  'Pawan',
  'Arindam Roy.',
  'MRITUNJAY',
  'Saumya',
  'Ansai',
  'Ajeet Singh',
  'DHARMENDRA SINGH',
  'Omji Pandey',
  'Harsh',
  'Amir Khan',
  'Divisha Pandey',
  'Shhshshsh',
  'Harshit Srivastava',
  'Gaurav',
  'Sourabh Yadav',
  'Alka Yadav',
  'Sudhanshu Singh',
  'Nit',
  'Sumit',
  'Sanjay Kumar',
  'Azeemul Haq',
  'ECE 03 Abhijeet Tiwari',
  'Shalini Singh',
  'Yatnish Manik',
  'Sonali Singh',
  'Sunmere Baat',
  'Sheetal',
  'SP',
  'Roony',
  'Sachin',
  'Aditya Saxena',
  'ASH',
  'Pooja Maurya',
  'Shobhit Singh',
  'Ankita',
  'Ashish Sharma',
  'Chhavi Nagar',
  'Aman Kumar',
  'Ã°Ââ€¢Â¾Ã°Ââ€“Å“Ã°Ââ€“â€ Ã°Ââ€“â„¢Ã°Ââ€“Å½ Ã°Ââ€¢Â¾Ã°Ââ€“ÂÃ°Ââ€“â€ Ã°Ââ€“â€”Ã°Ââ€“â€™Ã°Ââ€“â€',
  'Manoj',
  'Nitish Kumar Yadav',
  'Utkarsh',
  'Sammi Ben',
  'Suraj Kumar',
  'Rupali',
  'Ashish Agarwal',
  'Mohammad Hasan',
  'Avanish',
  'History Hindustan',
  'Senjuti De',
  'Ashish Kannaujiya',
  'Manali Jain',
  'Dandu Satvik',
  'Vineet Kumar',
  'Aman Agarwal',
  'Deepak Singh',
  'Aman Soni',
  'Ravi Kumar',
  'Pranav Singh',
  'Tricha Mishra',
  'Jatin Marwah',
  'Pradyumn Kumar Pandey',
  'Ayush Gupta',
  'Jaq Ray',
  'Rudra Pratap Pathak',
  'Ankit Yadav',
  'S.k',
  'Aayush',
  'Pushkrajman Singh',
  'Ã°Å¸Å’â„¢ni',
  'Prashant Kumar',
  'Manvi',
  'Divy Agarwal',
  'Abhimanyu Shukla',
  'Umang Sharma',
  'Aiman',
  'Divya',
  'Bhagya Rana',
  'Rudra Saksena',
  'Ritika Sarkar',
  'Shubham',
  'Chirag Chatwani',
  'Avnish',
  'Abd',
  'Lokesh N N',
  'Ranjeet Singh',
  'Sahaya Ray',
  'Aastha Aggarwal',
  'Moksh Dhangar',
  'Gunjan Sharma',
  'Ayush',
  '.',
  'Hrishit Jhaveri',
  'Nitesh Yadav',
  'Anurag',
  'Kaptan',
  'Gaurav Rai',
  'Rishabh K',
  'Rohit Ranjan',
  'Sitesh Muduli',
  'Divya Vijayakumar',
  'Mr. Tequila',
  'Umesh Upraity',
  'Priyanshu Chaudhary',
  'Dhruv Sharma',
  'Sonali Sharma',
  'Ankita Shahi',
  'Vishal',
  'Aadarsh Arya',
  'Ashish',
  'Vivek Kumar Kannaujiya',
  'Chandra Kanta',
  'AMIT SINGH',
  'MOJAMMIL ANSARI',
  'Abhijeet Bhattacharya',
  'Aalisha',
  'Abhishek Kumar Maurya',
  'Vijay',
  'Ashish Rai',
  'Teju',
  'Saurabh Singh',
  'Prince Singh',
  'Tanu Mishra',
  'Ak Kumar',
  'Rk',
  'HARSHVARDHAN MISHRA',
  'Fghj,',
  'Aparna Mishra',
  'Akhand',
  'Vaidish Srivastava',
  'Shreyansh',
  'Shashi',
  'A.V',
  'Sonali',
  'Satish Maurya',
  'Shahbaz Siddiqui',
  'Vikas Pandey',
  'Abhishek Yadav',
  'Sushant Kumar',
  'Utkarsh Saxena',
  'Aakriti Singh',
  'Shivam Malaviya',
  'Farhan Ejaz',
  'ANKUR PAL',
  'Udit',
  'Aradhy Tripathi',
  'Manish Kumar Giri',
  'Rajat',
  'Techno Problem Analysis',
  'Fahad Ata',
  'Deepika Vardhan',
  'Vaishnavi',
  'Ayush Srivastava',
  'Apoorv Krishna',
  'Suraj Patel',
  'Sagar',
  'Himanshu Agarwal',
  'Abhi Bhardwaj',
  'Ashutosh',
  'Madhur Savita',
  'Doojelal',
  'Sony Pandit',
  'Udit',
  'Krishna tripathi',
  'Amogh Singhal',
  'Lalit',
  'Ashish Kumar',
  'Bharti',
  'Harsh',
  'Elon',
  'Ankur',
  'Tt',
  'Sandeep Dixit',
  'Sandeep Dixit',
  'Abhijeet Singh Yadav',
  'Aastha Mishra',
  'Anand',
  'Shivam Kumar',
  'Ã°Ââ„¢Â°Ã°ÂÅ¡â€¹Ã°ÂÅ¡â€˜Ã°ÂÅ¡â€™Ã°ÂÅ¡Å“Ã°ÂÅ¡â€˜Ã°ÂÅ¡Å½Ã°ÂÅ¡â€ Ã°Ââ„¢Â¹Ã°ÂÅ¡â€˜Ã°ÂÅ¡Å',
  'Anjali Verma',
  'Ankita Yadav',
  'Pranjal Bhardwaj',
  'Shushant Singh',
  'Vicky',
  'Aditya Verma',
  'Sachin Kumar',
  'UDIT RAJPUT',
  'Siddhant',
  'Zunaid',
  'Shani Kumar Gupta',
  'Akash Agrawal',
  'Suraj Singh',
  'Shubham Jain',
  'Saurabh Kumar Singh',
  'Rocky',
  'NAVEEN CHANDRA GUPTA',
  'Deepika Srivastava',
  'Monendra Singh',
  'Rohan Kumar',
  'Preeti Shah',
  'Megha',
  'Rishabh',
  'Rohit Kushwaha',
  'Himanshi',
  'Ayushi',
  'Purvi Malik',
  'Priyanka Yadav',
  'Kapil Kumar',
  'Ruchi Kanaujiya',
  'Ashish Sharma',
  'Pradeep Kumar',
  'Shakshi',
  'Sriyansh Jain',
  'Sillent Killer',
  'Vaishnavi',
  'Amie Srivastava',
  'Vaishali Jain',
  'Kartik Agrawal',
  'Vipul Kumar',
  'Akshat Goyal',
  'Pankaj Kumar',
  'Ankit Bansal',
  'Aniket Solanki',
  'Shatakshi Singh',
  'Shivam',
  'Aditya Mukherjee',
  'VAAYU',
  'Aanchal Choudhary',
  'Kiran',
  'Sushmita Kaushal',
  'Shivani Chaudhary',
  'Neha Pandey',
  'Harshita Singh',
  'Megha Agrawal',
  'Uddhav Sankhdhar',
  'Naina',
  'Swanjali Singh',
  'Subhojit Mitra',
  'SHIVAM GUPTA',
  'Vivek',
  'Akash Babu',
  'Narsingh Narayan Pandey',
  'T',
  'Mohd Ubaid',
  'Abhishek Kumar Singh',
  'Ankit',
  'Anurudha Pratap Singh',
  'RUDRENDRA DUBEY',
  'Deepanshu Saini',
  'Suraj',
  'Srijan Tripathi',
  'Akash Katiyar',
  'Komal Singh',
  'Ankit',
  'Pankaj Yadav',
  'ANKIT KUMAR MODANWAL',
  'Astha Singh',
  'Prateek Mishra',
  'Vivek Kumar',
  'Aparajita Kumari',
  'Mohhammad',
  'Tanmay',
  'Atish Sonkar',
  'Sajal Gupta',
  'Yahoo',
  'Alok Singh',
  'Jay Kishan',
  'Dev Yadav',
  'Pankaj Kumar',
  'Sameer Pandey',
  'Akhilesh Kumar Singh',
  'ANOOP R',
  'Satyam Tripathi',
  'Deepak',
  'SATYAM SHUKLA',
  'Saurabh Kumar',
  'ALOK KUMAR',
  'Gaurav',
  'Abhyanshu Yadav',
  'Raunak Chaurasia',
  'RANI',
  'Ayush',
  'Abhishek Chaudhary',
  'Anshita Arora',
  'Ritik',
  'Saurabh Rathor',
  'Mudit Rayvoria',
  'Reema Kumari',
  'Aakarshita Srivastava',
  'Shardul Singh',
  'Rydam Agrawal',
  'Ashwini Singh',
  'NISSAR AHMED',
  'Shreya Gupta',
  'Sakshi',
  'Piyush Agnihotri',
  'Rishabh Mathur',
  'Abhinav Soran',
  'Aditya Rai',
  'Satyam Tiwari',
  'Samiksha Jain',
  'Kamal Kant',
  'Sabhajeet Yadav',
  'Yadav Shiykhar',
  'Devesh Sharma',
  'Deepanshu Yadav',
  'Vipin Chandra Valmiki',
  'Ashi Saini',
  'Aman Maurya',
  'Mala Kumari',
  'Abhishek',
  'Shaiffali Sharma',
  'Shivam Kumar',
  'Farhaan',
  'Akhilesh Kumar Mishra',
  'Shruti Sharma',
  'Ajay',
  'Aman Khan',
  'Sourabh',
  'Deepanshi Vashistha',
  'Kshitiz Rajesh',
  'Shivani',
  'Priyanshu Shekhar Pandey',
  'RITESH KUMAR',
  'Sajal Misra',
  'Saurabh Kumar Singh',
  'Divakar Pal',
  'Brajesh Kumar',
  'Harshita',
  'Manu Gupta',
  'Praveen Kumar Gupta',
  'Rahul Kumar',
  'Sumit Kumar',
  'Anvesh Pandey',
  'Shivam Kharwar',
  'Surbhi Gautam',
  'Aviral Sahu',
  'Abhishek Gupta',
  'Imteyaz Khan',
  'Akhand Pratap Yadav',
  'Ankit Maurya',
  'Om Jee Shrivastava',
  'Govind Kaushik',
  'DIVYANSH OMAR',
  'Vaibhav',
  'Mansi',
  'Amit Tripathi',
  'Navneet Vishwakarma',
  'Sakshi Singh',
  'Anchal Mishra',
  'Archit Pandey',
  'Piyush Sharma',
  'Kartikay Singhal',
  'Saumya Pateriya',
  'Mukul Garg',
  'Deeksha Singh',
  'Kavish Kumar',
  'Vikrant Singh',
  'Saumy Kumar Mishra',
  'Govind',
  'Raghav',
  'Ishika Jaiswal',
  'Mohd Sadiq',
  'Prajwal',
  'Aparajita Asthana',
  'Abhishek Madhesiya',
  'ABHISHEK KUMAR',
  'Jatin',
  'Kunal Aggarwal',
  'Manish Sharma',
  'Shatakshi',
  'Shashank Mishra',
  'Anand Tiwari',
  'Nikhil Chauhan',
  'NITIN SHARMA',
  'Prince Kumar Chaudhary',
  'Rishabh',
  'MD Azam Khan__041',
  'Rupesh Kumar',
  'Divyanshu',
  'Ujjwal Agarwal',
  'Imran Ansari',
  'Laxmi Narayan Vishwakarma',
  'Brijesh Varun',
  'Prashant',
  'Harsh',
  'Priya',
  'Satyam',
  'Kartikay',
  'Ajay Kumar',
  'Gyanu',
  'Adity Kumar',
  'Ty',
  'Arpit Dubey',
  'Manish Rawat',
  'Ayush Tyagi',
  'Surya Thakur',
  'Sid Mishra',
  'Sahil Azad',
  'Ritik Pal',
  'Praveen',
  'MRINAL SANGYA',
  'Piyush',
  'Akash',
  'Rishabh Tripathi',
  'Naveen Singh',
  'Ashish',
  'Kavita Kardam',
  'Satyam Yadav',
  'Saurabh Shukla',
  'Praveen Kushwaha',
  'Divyanshi Pandey',
  'Aman Burman',
  'Balak Ram',
  'Adarsh Shrivastav',
  'Rohit Sharma',
  'KARAN KUMAR',
  'Priyansh',
  'Abhishek Gupta',
  'Amaml',
  'VIVEK',
  'Radhe Saurabh',
  'Yash Garg',
  'Prashant Singh',
  'Ashmita Bajpai',
  'Anupam Kumar',
  'Devendranath Gupta',
  'Shreya',
  'Amish',
  'Arun Kumar Singh',
  'Ashmita Bajpai',
  'Ravikaran Srivastava',
  'Priyansh',
  'Priya Gupta',
  'Vaibhav Dubey',
  'Vineet Srivastava',
  'Agam Gupta',
  'Shravan Kumar Jaiswal',
  'Ashish Kumar',
  'YOGESH PAL',
  'Uday Chauhan',
  'Vikash',
  'ANKUL YADAV',
  'Ashna Khan',
  'Manish',
  'Rishi Kumar Soni',
  'Mo Parvej',
  'Pradeep Singh',
  'Ansh Kumar',
  'Ashish  Yadav',
  'Ansh Kumar',
  'Ã Â¤Â°Ã Â¤Â¾Ã Â¤Â® Ã Â¤Â¬Ã Â¤Â¹Ã Â¤Â¾Ã Â¤Â¦Ã Â¥ÂÃ Â¤Â°',
  'Harish Prasad',
  'Aishwarya Katyal',
  'Priyanshu Chaurasiya',
  'Radhika Devi',
  'Ashish Kumar',
  'Ashmita Bajpai',
  'Sumit Kumar Srivastava',
  'Honey',
  'Shashi Kumar Gupta',
  'Mayank Sharma',
  'Anant Mani Tiwari',
  'Aktulol',
  'Shubham Kumar Prajapati',
  'Apoorva',
  'Samin Ansari',
  'Raghvendra Pratap Singh',
  'Keshav Arora',
  'Shruti Jain',
  'Gautam Sahyogi',
  'Sudhanshu Shrotriya',
  'Palash Sharma',
  'Ayush Mishra',
  'Shivam Saxena',
  'Sneh Kant Sharma',
  'Khushal Varshney',
  'Suraj',
  'Ahmad Hamza Khan',
  'Radha Singh',
  'Anirudh Raghav',
  'Ayushi Goel',
  'Prince Kumar Kanoujiya',
  'Vikas Kumar Patel',
  'AMAN SAHU',
  'Pranjal Gupta',
  'Son Goku',
  'Rahul Singh',
  'Aman Kumar Gupta',
  'Babu',
  'Mehtab Ansari',
  'Bharti Gorai',
  'Shavez',
  'Awadhesh Prajapati',
  'Preeti Jaiswal',
  'Rajat Pratap Singh',
  'Golu',
  'Garima Mittal',
  'Dgjjjn',
  'Akanksha Gupta',
  'Sumit Verma',
  'Ishika Mittal',
  'Somi Siddiqui',
  'Gaurav',
  'Satyam Singh',
  'Anany Srivastava',
  'Saurabh Kumar',
  'Ajay Kumar',
  'Aditi Maheshwari',
  'Harshit Srivastava',
  'Anisha Singh',
  'Rishabh',
  'Aditya Verma',
  'Ayush',
  'Dharmpal Rajput',
  'Shreyansh Sahai',
  'Rose Gupta',
  'Anya Tripathi',
  'Ashish Kumar Chaurasiya',
  'Mahek Singhal',
  'SHIVSINGH RAJPUT',
  'Vikram',
  'Sanjeev',
  'KM SARITA PATEL',
  'Chandra Shekhar Kumar',
  'Ayush Rastogi',
  'Priyal Goel',
  'Satakshi Singhal',
  'PAWAN MUDGAL',
  'Sanjay Kumar',
  'Priyanshu Verma',
  'Waseem Ahmad',
  'Akshay Ahlawat',
  'Abhijeet Singh',
  'Mukul Singh',
  'Jatin Sharma',
  'DIWAKAR KUSHWAHA',
  'Bilal Ahmad',
  'Shashi Prabha Raj',
  'Harshit Srivastava',
  'Er Shivam Singh',
  'Adarsh Shukla',
  'Ashish',
  'Akash Singh',
  'Shubham',
  'Rajendra Kumar',
  'Nitesh',
  'RISHANK BHARDWAJ',
  'Saurabh',
  'Abhishek Gupta',
  'Anjali Singh',
  'Meghana Prajapati',
  'Sani Mewati',
  'PRT Admun',
  'REEMA MADDHESHIA',
  'Nayyare Alam',
  'Akash Bharadwaj',
  'Deepak Singh',
  'Saurabh Mishra',
  'Paramatma Kumar Gautam',
  'Sudhakar Singh',
  'Manish Pandit',
  'Chittaranjan',
  'Anshul',
  'Ishank Goel',
  'Akhil',
  'Keshav Chauhan',
  'SUMIT KUMAR',
  'Yuvraj Singh',
  'Nitish Saini',
  'Kaushal',
  'Sachin',
  'Shiv Kant',
  'Ashutosh',
  'Swapnil',
  'Durgesh Kumar',
  'Maneesh Singh',
  'Ayush Agarwal',
  'Pramod Kumar',
  'Prashant Chaudhary',
  'ANUJ',
  'Sunilkumar',
  'Mk Sikander',
  'ABHISHEK KUMAR',
  'Lakshya Chaturvedi',
  'Amit',
  'Abhishek Kumar',
  'Satyam Kumar',
  'Indrjeet Pandey',
  'Monika Yadav',
  'Divyanshi Mishra',
  'Manu',
  'Aditya Kumar',
  'Aalok Verma',
  'Saurabh Modanwal',
  'Kanishka Rani',
  'Sagar',
  'Sudhanshu Gupta',
  'Shanaya',
  'Srishti Singh',
  'Ganesh Kumar',
  'Niraj Jaiswal',
  'Abhinay Srivastava',
  'Ankit Dubey',
  'Yash Verma',
  'Rajneesh Kumar',
  'Rajneesh Kumar',
  'Ayushi Tyagi',
  'Mudasir',
  'Jyoti Jaish',
  'Pandat',
  '6',
  'HeeraLal',
  'Palak Garg',
  'Shivam Pal',
  'Alkaraj',
  'Nitendeep Singh',
  'Divyansh Kumar Singh',
  'Aditya Tiwari',
  'Priyesh Singh',
  'Ashish Sharma',
  'Vivekanand Singh',
  'Aman Kanaujiya',
  'Anurag',
  'Shivani Gupta',
  'Sanchit',
  'Eshu Goyal',
  'Sanjeev Kumar Yadav',
  'Prashant Singh',
  'Shashank Rai',
  'Rakesh Kumar',
  'Abhiman',
  'Aman',
  'Aniket',
  'Niharika',
  'Shwetank Mishra',
  'Palak Singh',
  'Shivam Verma',
  'Sakaham Pandey',
  'Saurabh',
  'Satyajeet Singh',
  'Pratyush Bharti',
  'ARBAJ',
  'Rachana Chaurasiya',
  'Sandeep Kumar Sant',
  'Sankalp Singh',
  'Jitendra Kumar',
  'Shradha Saini',
  'Shubham Baranwal',
  'Divy Shukla',
  'Vedant',
  'Rakesh',
  'Divy Shukla',
  'Shubham Jain',
  'Madhu',
  'MAYANK PAL',
  'Vikas Vashistha',
  'Arun Shrivastav',
  'Shawez Ansari',
  '...',
  'Charu',
  'Aditya',
  'Ajay Tiwari',
  'Lucky',
  'Anushka Mishra',
  'Aman',
  'Pulkit Mittal',
  'Neeraj Kumar',
  'Rishita',
  'Manish Parihar',
  'Abhishek Kumar',
  'Aryan Singh',
  'Aryan Verma',
  'Pinki Saini',
  'Pratham',
  'Arpita Gupta',
  'Vishal Rai',
  'Kavya Agrawal',
  'Pooja Chaudhary',
  'Pradumn Gupta',
  'Alok',
  'Siddhant Srivastava',
  'Kavya',
  'Pankaj Singh',
  'Chandradeep Kumar',
  'VINAY KUMAR',
  'Rahul Mishra',
  'Shivam Anand',
  'Shriya Shukla',
  'Ankit Singh',
  'Akbar Shikoh',
  'Gaurav Shakya',
  'Shivam Dwivedi',
  'Ata Husain',
  'DEEPAK MAURYA',
  'Shubham Singh',
  'Akash Pratap',
  'Faiz Anwar',
  'Snehal Rajvansh',
  'Kashish Gupta',
  'Uday Rajveer',
  'Vandita Shukla',
  'Avindra Singh',
  'Vishwa Gaurav Shukla',
  'Sudheer Singh',
  'Ã°Å¸â„¢Â',
  'SHIVAM SRIVASTAVA',
  'KARAN VEER SINGH',
  'Vishwas Verma',
  'Yash Gupta',
  'BIMAL JALAN',
  'Siddharth Samanta',
  'Manas Saxena',
  'Ashutosh Kumar',
  'Yashraj Kumar',
  'Avinash Mathur',
  'Ishika Lamba',
  'Vishal Sharma',
  'Atisarv Verma',
  'Arpan Malik',
  'Shivalaya',
  'Madhu',
  'Amit Kumar',
  'Divyansh Mathur',
  'Tarun Singh',
  'Manya Rastogi',
  'Shreya',
  'Abhishek Singh Parihar',
  'Anushka Shukla',
  'Harshit Srivastava',
  'S',
  'Vedic88',
  'Bhrigunath',
  'Nitesh',
  'Nita Singh',
  'Akanshu Rana',
  'Harsh Kansal',
  'Megha Gupta',
  'Manish Sharma',
  'Pooja',
  'APARNA SHARMA',
  'Urvashi Gupta',
  'Ayushi Singh',
  'Vicky Singh',
  'Ekansh Gupta',
  'Divyanshu Gupta',
  'Devansh Kumar',
  'Mahima Singh',
  'Garvit',
  'Anirudh Gupta',
  'Anand Singh',
  'Shashi Singh',
  'Amar',
  'Shruti Kumari Agrahari',
  'Sghbb',
  'Shailesh Chandra Dubey',
  'Mr. J. K. Singh',
  'Nikhil Maurya',
  'Akhil Kumar',
  'XYZ',
  'Tushar Tyagi',
  'Arman Singh',
  'Happy',
  'Shubham Singh',
  'Vipin',
  'Mansi Singh',
  'Nirbhay Singh',
  'Shivank Sharma',
  'Aasif Saifi',
  'Anurag Yadav',
  'Atul',
  'Siddhartha',
  'Ankit',
  'Saumya Srivastava',
  'Shoaib Akhtar',
  'Sumit',
  'Bhavya',
  'Sachin Kumar',
  'Vineet',
  'My Way',
  'P Rohit',
  'Shobhit Srivastava',
  'SACHIN..52',
  'Vikas Chaudhary',
  'Kamlesh Maurya',
  'Ketan Singh',
  'Tony',
  'Harsh Vardhan Tripathi',
  'Rishabh Saroj',
  'Aryan Sharma',
  'Manas',
  'Kshitiz',
  'Nikita',
  'Anees',
  'Manish',
  'Mradul Pachauri',
  'Anshul Gupta',
  'Uday Pratap Singh',
  'Rajit',
  'Anjali Sharma',
  'Gaurav Sharma',
  'Vishal',
  'VIKASH KUMAR SINGH',
  'Abhishek Tomar',
  'Silky',
  'Rohit Chauhan',
  'Yash Srivastava',
  'Ajit Kumar',
  'Prateek Shukla',
  'Gaurav Sharma',
  'Nirbhay Pratap Shrivastava',
  'Hritik Singh',
  'Kuldeep Yadav',
  'Mohammad Aariz',
  'Aditya',
  'Abhiraj',
  'Nitish Kumar Jha',
  'Jayshree',
  'Vaibhav Jain',
  'Shanu',
  'Ankit Kumar Gupta',
  'Shaiz',
  'Deep Kushwaha',
  'Mansi Gupta',
  'Niraj',
  'Shubham Bandhu',
  'Murari Jee',
  'Dinesh Singh',
  'Vishal',
  'Harsh Jangid',
  'Obscure',
  'Aditya Saxena',
  'Swapnil Mishra',
  'Manish',
  'Rahul',
  'Chandra Shekhar Prasad',
  'Manish',
  'Sheeba',
  'Abhishek Pandey',
  'Nitin Goel',
  'Akshat',
  'Sakshi Verma',
  'Avinash Kumar',
  'Riya',
  'Misbauddeen',
  'Shikha Rai',
  'Radhe',
  'Mohit Chaudhary',
  'Logan',
  'Sidd',
  'Vijay Singh',
  'Ranjit Kumar',
  'Vijay Singh',
  'Vivek Kumar Mishra',
  'Shivansh Amit Srivastava',
  'Atul Yadav',
  'Archana Singh',
  'Shubhi Srivastava',
  'Vinay Kumar Gautam',
  'Suarya',
  'Avanish Chandra Pandey',
  'Navin Kumar Shahi',
  'Shivam Singh',
  'Rahul',
  'Tushar Arya',
  'ASHUTOSH',
  'Deepak Kumar Singh',
  'Praveen Kumar Singh',
  'Vikas Kumar Tiwari',
  'Utkarsh Singh',
  'Ruchi Yadav',
  'Dank 5',
  'Mayank',
  'Brhamin',
  'Aditya Narayan',
  'GOVIND KUMAR YADAV',
  'Luv Pratap Singh',
  'Tushar Singh',
  'Sand',
  'Kabir Pratap Singh',
  'Vinay Singh Yadav',
  'Pankaj Kumar',
  'Ki',
  'Himanshu',
  'Shubham Gupta',
  'Mayank Rawat',
  'RAJ SONKAR',
  'Akarshan Keshri',
  'Amit',
  'Aakash Jaiswal',
  'Akash Yadav',
  'Shashank',
  'P',
  'Divya Shukla',
  'Jagriti Gupta',
  'Aman Lodhi',
  'Aman',
  'Brishti Tikadar',
  'Mukesh Kumar Gupta',
  'Kumar Gaurav Pandey',
  'Anmol Agarwal',
  'Shraddhanjali Gupta',
  'Shresth',
  'Mohit Jauhari',
  'Mohammad Anas',
  'Ravindra Yadav',
  'Ashish Chauhan',
  'Disha Srivastava',
  'Tushar Rashm',
  'Abdus Sami',
  'Gulshan Bano',
  'Rajeev Kumar Gupta',
  'Aayushi',
  'Durgesh Kumar',
  'Indian Famaly',
  'Srj',
  'SACHIN KUMAR',
  'Humaid Ansari',
  'Satyam Rajput',
  'Nishu',
  'Rachit Khare',
  'Aman Maurya',
  'Himanshu Baranwal',
  'Dr Anushri',
  'Himanshu Jaiswal',
  'Jagdeep Gupta',
  'Chidu',
  'Zubair',
  'Abhishek Singh',
  'Mansi Sahu',
  'Anushka Kanaujia',
  'Shristi',
  'Arun Kumar Teotia',
  'Akshay Pandey',
  'Saurabh Singh',
  'Aditya Tiwari',
  'Manish Kumar Chaurasia',
  'Ashok',
  'Sachin Kumar Mandal',
  'Jyoti',
  'Shad Siddiqui',
  'Somesh Srivastava',
  'Ansuman Pandey',
  'Sonia',
  'Alokito',
  'Nikhil Mishra',
  'Ankur Rawat',
  'RAAJ',
  'Shubham Chandra',
  'Ankit',
  'Love',
  'Kapil Kumar',
  'Rahul Ojha',
  'Babu Kumar',
  'Ritik Verma',
  'Ashish Yadav',
  'Anjali',
  'Vikas Bharti',
  'Megha',
  'Dheeraj Kumar Yadav',
  'Prashant Kumar Chaudhary',
  'Vicky Chaudhary',
  'Aradhya',
  'Raees',
  'Shipra',
  'Prince Pandey',
  'Samikant Yadav',
  'Abhinav Pratap Singh',
  'Vibhav Pratap Singh',
  'Devansh Maurya',
  'Swapnil Sharma',
  'Rahul Rajput',
  'Gopal Bhardwaj',
  'Rahul Kumar',
  'Jigar',
  'GOPAL GUPTA',
  'Rajan Gautam',
  'Namrata Rawat',
  'Satyam Mishra',
  'Arpit Singh',
  'Santosh Kumar',
  'Suhani',
  'Satyam Shivam',
  'ASHWIN BHARTI',
  'Atul Kumar',
  'Umakant Mishra',
  'Sagar Tanwar',
  'Anil Kumar',
  'Praduman',
  'Praduman',
  'Vikash Pathak',
  'Praduman',
  'Anshul Kumar',
  'Prashant Srivastava',
  'Prince Verma',
  'Goku',
  'Aman Kumar Singh',
  'Mr Venom',
  'Suhel',
  'Sachin Sharma',
  'Amit Ranjan Kumar',
  'Abhi',
  'Paritosh Verma',
  'Anuj',
  'Ishaan',
  'ASHISH RANJAN',
  'Shikhar Srivastava',
  'Achintya',
  'Bilal Hashmi',
  'Asheesh',
  'Rakesh',
  'Siddhartha Srivastava',
  'Prakhar Srivastava',
  'Shivam',
  'AKHIL Singh',
  'Anya Gupta',
  'Prince Kumar',
  'Deepak',
  'Amanpreet',
  'Vikas Saroj',
  'Digvijay Gupta',
  'Ajay Singh Yadav',
  'Uttam Kumar',
  'Satendra Kumar',
  'Gaurav Shakya',
  'Pranjal Chaudhary',
  'Raja Gupta',
  'Gaurav',
  'Arvind Chaudhary',
  'Gaurav Kumar',
  'Virendra Pal',
  'ANUJ GUPTA',
  'Vipin Mishra',
  'Varun Prajapati',
  'Adarsh Kushwah',
  'Anya Gupta',
  'Himanshu Sharma',
  'Ratnesh Chaubey',
  'Ashutosh Dwivedi',
  'Abhinandan',
  'Arimardan Rai',
  'Abhishek Maurya',
  'Nishant',
  'Vinay Kumar',
  'Peyush Kumar Yadav',
  'Anshu Kumar',
  'Saket Singh',
  'Mahima Rai',
  'Chirag Rastogi',
  'Piyush Srivastava',
  'Mohd Talib',
  'Mainuddin Ansari',
  'Sanaullah Ansari',
  'Aman Singh',
  'Nitish',
  'Aman Kaushik',
  'Asad Suhail',
  'Aditya Srivastava',
  'Abhinav',
  'Sid',
  'Divya',
  'Asad Suhail',
  'Uday Kumar',
  'Xyz',
  'Aman Rai',
  'Himanshu Kumar',
  'Vishal Shukla',
  'MR',
  'Somnath Suman',
  'Chakshu Khajuria',
  'Prashant Yadav',
  'Skand Tripathi',
  'Ritik Singh',
  'Rakhi Biswas',
  'Vinay Vishwakarma',
  'Nadeem Fazal',
  'Aditya Singh Yadav',
  'Prashant Kumar',
  'HARSH PRATAP',
  'Vaibhav Kesarwani',
  'Ritesh Yadav',
  'Taukir Khan',
  'Anjana Sharma',
  'VINAY CHAUBEY',
  'Anjana Sharma',
  'Gaurav Kumar',
  'Aayush',
  'Abhay',
  'Anshiii Kushwaha',
  'Shweta',
  'Amit Bhaskar',
  'Shivam Yadav',
  'Akash Kumar',
  'Updesh Pandey',
  'Bhavrendra',
  'Pooja',
  'Nisha Gautam',
  'Shams Rabbani',
  'Mata Prasad Yadav',
  'Rayan Singh',
  'Vrinda',
  'Aman Kumar Harsh',
  'TIGER SHROFF',
  'Faijan',
  'Sonam',
  'Suraj Chaurasia',
  'Rishi Agarwal',
  'Devesh',
  'Shikha Pandey',
  'Riya Tiwari',
  'Aayush',
  'Srishti Kaushik',
  'Vishal Shekhar',
  'Dheerajvimal',
  'Janvi Tyagi',
  'AJ',
  'Vishal Sharma',
  'Shweta Sharma',
  'Shikha',
  'Ankur Singh',
  'Avanish Gupta',
  'Ashish Pandey',
  'Babu Rao',
  'Shivam',
  'Harsh Tripathi',
  'Kushagra Patel',
  'Ayush Singh',
  'Avanish Gupta',
  'Shivam',
  'Sudhanshu Bhardwaj',
  'Rajit Kumar',
  'Kj',
  'Abhay Agarwal',
  'Siddhant Pegowal',
  'Mehboob Malik',
  'Varun Dixit',
  'Harsh Singh',
  'Allu',
  'Manish Kumar',
  'Ajad Ansari',
  'Ankit',
  'Nehul',
  'Neeraj Pandey',
  'A.Kumar',
  'Adesh',
  'Rishabh Jain',
  'Abhishek',
  'Abhishek Singh',
  'Urvashi Trivedi',
  'Rahul Sharma',
  'Raj',
  'Riaan',
  'Rajkumar Yadav',
  'Vi Y',
  'Shalvi Paliwal',
  'Sonu Yadav',
  'Karan Rawat',
  'Amit Pratap Singh',
  'Rahul Yadav',
  'Aman Prakash',
  'Mridul',
  'PANKAJ KUMAR',
  'Pradeep Kumar',
  'Adarsh Kumar Singh',
  'UTKARSH',
  'Punjesh Sharma',
  'Sashikant Joshi',
  'TECHNICAL SURENDRA',
  'Kunj',
  'Puru Poriya',
  'Gaurav',
  'NAYAN KUMAR',
  'Swati Kiran',
  'Akash Saroj',
  'Nitish Kumar',
  'Brjesh Kumar Verma',
  'Shivam Trivedi',
  'Deshdeep',
  'Atul Yadav',
  'Sourav',
  'Umashankar',
  'Apoorva Srivastava',
  'Divya Srivastav',
  'Lav',
  'Prabhat',
  'Mohd Muzzammil Khan',
  'Abhishek',
  'Satyam Tripathi',
  'Pranjal',
  'Rahul Sharma',
  'MUKUND KHAITAN',
  'RAMPRATAP Kushawaha',
  'Rishabh Chauhan',
  'Ayush',
  'Ankit',
  'Raj Pratap Singh',
  'PRAVEEN KOTARYA',
  'Ritik Singh',
  'Umesh',
  'Deepak Patel',
  'Suryansh Mishra',
  'Shivam',
  'Navnit Ray',
  'Maisar Khan',
  'Nishant Kr. Dubey',
  'Prachi',
  'PRACHI CHAUHAN',
  'Vishal Chaudhary',
  'Utkrishta',
  'DYBAMO GAMING',
  'Harshit PAL',
  'Ilma Ansari',
  'Lalit',
  'Naman Singhal',
  'Suraj Kumar',
  'Tausif',
  'Kirti Singh',
  'Lavkush Singh',
  'Mahendar Kumar',
  'Ajay Chaudhary',
  'Anup Kumar Tiwari',
  'Mridul Tiwari',
  'Yatender Singh',
  'Prince Kumar Bharti',
  'Swati Singh',
  'Princy Sahu',
  'Shivani Savita',
  'Golden Sharma',
  'Thakur Bhanu Pratap Singh Suryavanshi',
  'Rudramani Pandey',
  'Shivani Savita',
  'Rohit Gupta',
  'Sagar Pal',
  'Abhi',
  'Manish Kumar Yadav',
  'Puneet',
  'Ayusnhi Verma',
  'Ashish Kumar',
  'Amul Kumar',
  'Vishwas Mishra',
  'Shubham Gupta',
  'Avani Tyagi',
  'Sushant Shekhar',
  'Suryansh Rai',
  'Rebrl',
  'Aman Tripathi',
  'SOURABH DUBEY',
  'Rahul Kumar',
  'Shweta Pandey',
  'Krishna Joshi',
  'Nidhi Maddhesiya',
  'Saksham',
  'Puneet Gupta',
  'Arunika Srivastava',
  'Rishabh Sahu',
  'Drago',
  'Sha',
  'Manish Kumar',
  'Brijesh Kumar Sonkar',
  'Sarita Verma',
  'Chaitanya  Tayal',
  'Upendra Yadav',
  'Faiz Abbas',
  'Shraddha Kasaudhan',
  'Subham Kumar Sharma',
  'Shristi Srivastava',
  'Udit Kumar',
  'Abhijeet',
  'Mohd. Suhaib Kidwai',
  'Ishaq',
  'Komal Yadav',
  'ROHIT YADAV',
  'Komal Yadav',
  'Jitenda',
  'Saif Ali',
  'Sundram Awasthi.',
  'Satyam Verma',
  'Google',
  'Pankaj Singh Bhakuni',
  'Sahil',
  'Ankit Pandey',
  'Chandan',
  'Saurabh Mishra',
  'Nitin',
  'A.C',
  'Deepanshu',
  'Pushpendra Kumar',
  'Anshul Kushwah',
  'Roshan Pandey',
  'Rana',
  'Amit Yadav',
  'Spychamp',
  'Wajiha Raza',
  'Kratika Mishra',
  'Abhishek Singh',
  'Aman Patel',
  'Deepak',
  'Adarsh Patel',
  'Artikpal665',
  'Ratanpriya Tiwari',
  'Sakshi Kashyap',
  'Pratush Jain',
  'Sakshi',
  'A',
  'Sarvani',
  'Vishal Sharma',
  'Rajan',
  'Kc',
  '#yaduvanshi',
  'Kripa Sindhu Pandey',
  'Akshat',
  'Anchal Chauhan',
  'Sachin Yadav',
  'Apoorv',
  'Pavan Srivastava',
  'Sonam Sahni',
  'Sarthak Singh',
  'Himanshu Pandey',
  'Rachit Soni',
  'Raj',
  'Akash Pandey',
  'Mahesh',
  'Prakash Singh Negi',
  'Omkar Jaiswal',
  'Amit Kumar',
  'Priyanshu Raj',
  'Vikash Gaurav',
  'Shivam Singh',
  'Umesh Valmiki',
  'Aakash',
  'Divyansh',
  'Himanshu Raj',
  'Rahul Kushwaha',
  'Amar Nath',
  'Rishi Chhabra',
  'Raj',
  'Shiwani Goyal',
  'Chandan Pandey',
  'Shivendra Gupta',
  'NEEEAJ SHUKLA',
  'Pratiksha',
  'Mukul',
  'Akash Dubey',
  'Arjun Pal',
  'Mansi Kumari',
  'Abhay Pratap Singh',
  'Abhishek Kumar Jha',
  'Shivani Datta',
  'Shivam',
  'Amar Nath Rai',
  'Robin',
  'Deepak Yadav',
  'Gaurav Sharma',
  'Shivam',
  'Akshay Gireesh',
  'Prashant Singh',
  'L',
  'Amir Khan',
  'Ekansh Sahu',
  'Pranjal',
  'Nikita Singh',
  'Syed Md Saifi Hassan',
  'Nourin Ansari',
  'Aashna',
  'Shivam Mishra',
  'Sourabh Verma',
  'Harsh Deol',
  'Anup Bharti',
  'Ankit Kumar',
  'Aaryavan',
  'Rohan Kumar',
  'Dibendu',
  'Abhishek  Kumar',
  'Satish Kushwaha',
  'Sagun Chaudhary',
  'Ashutosh Kumar Anshu',
  'Anurag Prajapati',
  'Shubham Pandey',
  'Deepak Kumar Maurya',
  'Jasdeep Singh',
  'KARAN MATHUR',
  'Shruti Agarwal',
  'Abhishek Kumar Yadav',
  'Anup Kashyap',
  'Mohit Chandela',
  'Harsh',
  'Pk',
  'Pro',
  'Avi',
  'Shubham Sinha',
  'D Lucky',
  'Shivam Aggarwal',
  'Shivangi Dubey',
  'AVINASH Singh',
  'Sudhanshu Pandey',
  'Brijesh',
  'Nilay Sharma',
  'Kajal Chauhan',
  'Sumit',
  'Nitu Singh',
  'Jatin Pandey',
  'Ritu',
  'Abdul Mazid',
  'Bharat Singh',
  'Pooja Kumari Jaiswal',
  'Nisha Singh',
  'Tasnim Iqbal',
  'Test',
  'Abhishek Yadav',
  'Ravi__',
  'ASHANK',
  'Gaurav',
  'Ankit Yadav',
  'Saurabh Pal',
  'Preet Bansal',
  'Ankit Joshi',
  'Anand Kumar Jha',
  'Prakarsh',
  'Ashutosh Singh',
  'Ishan Parashar',
  'Priyanka Yadav',
  'Shanky',
  'Harsh',
  'Nihal Singh',
  'Sachin Kumar',
  'Avinash Chandra',
  'Ankit Kumar',
  'Rohit Sharma',
  'Shashank Sharma',
  'Ankur Goswami',
  'Mohit Yadav',
  'Rahul Kumar Pandey',
  'Ankur Singh',
  'Akash',
  'Mayank',
  'Vaishnavi Kumari',
  'Jaya Rastogi',
  'Rupali Gupta',
  'Ritu Rawat',
  'Roshan',
  'Anuj Verma',
  'Payal',
  'Rabin Kumar',
  'Ayushi',
  'Harshita Arun',
  'Aviral Kumar',
  'Shweta Maurya',
  'K',
  'Shivani Sharma',
  'Gaurav Singh',
  'Rajneesh Kushwah',
  'Abhishek Mishra',
  'Harsh Kashyap',
  'Abhi',
  'Abhi',
  'Priyanka Yadav',
  'Roshankanojia',
  'SNEHA PRASAD',
  'Ravi Kumar',
  'Divyansh',
  'Sandeep Kumar',
  'Misha Raj',
  'Kritika',
  'Jayesh Rawat',
  'Kajal Kumari',
  'Shivam Mishra',
  'Shiv Kumar Vishwakarma',
  'Akshay Upadhyay',
  'Khushbuddin Alam',
  'Mangaljeet Pandey',
  'Utpal Anand',
  'Vaibhav Bhardwaj',
  'Suraj Kumar Dhusiya',
  'Aayushi',
  'Rahul Kumar',
  'Amal',
  'Shekhar Saini',
  'Harshit',
  'Mahima Pandey',
  'Nikhil Singh',
  'Neha Maurya',
  'Deeksha Dubey',
  'Kaushal',
  'Rohit',
  'Shreyansh Gupta',
  'AKSHAY Raj',
  'Ajay Pratap Singh',
  'Muskan',
  'Roshni Bano',
  'Naveen Jaiswal',
  'Mohd Hadi',
  'Abhishek',
  'Divyansh Jaiswal',
];

export const images = [
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/8.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/11.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/12.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/13.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/14.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/15.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/16.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/17.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/18.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/19.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/20.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/21.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/22.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/23.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/24.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/26.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/27.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/28.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/29.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/30.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/31.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/32.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/33.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/34.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/35.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/36.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/37.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/38.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/39.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/40.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/41.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/42.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/43.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/44.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/45.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/46.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/47.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/48.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/49.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/50.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/51.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/52.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/53.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/54.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/55.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/56.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/57.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/58.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/59.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/60.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/61.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/62.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/63.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/64.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/65.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/66.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/67.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/68.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/69.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/70.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/71.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/72.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/73.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/74.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/75.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/76.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/77.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/78.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/79.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/80.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/81.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/82.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/83.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/84.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/85.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/86.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/87.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/88.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/89.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/90.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/91.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/92.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/93.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/94.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/95.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/96.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/97.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/98.png',
  'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/99.png',
];
